#! /usr/bin/env python

import sys

f = file(sys.argv[1],'r')
fdata = f.readlines()
f.close()

for line in fdata:
    if line.startswith("#"):
        print line.strip()
    else:
	row = line.strip().split("\t")
	ref = row[3]
	alt = row[4].split(",")
	for alt_allele in alt:
	    if alt_allele == ref:
                continue
	    else:
		print "\t".join(["\t".join(row[:4]),alt_allele,"\t".join(row[5:])])
