#! /bin/bash

# Remove files generated by single sequence alignment

export output_dir=runs/$1/$2

rm -rf ${output_dir}/*.fastq.gz
rm -rf ${output_dir}/*.sam.gz
rm -rf ${output_dir}/*.srt.bam
rm -rf ${output_dir}/*.srt.bai
rm -rf ${output_dir}/*.fxmt.bam
rm -rf ${output_dir}/*.fxmt.bai
rm -rf ${output_dir}/*.fxmt.bam.bai
rm -rf ${output_dir}/*.rmdup.bam
rm -rf ${output_dir}/*.rmdup.bai
rm -rf ${output_dir}/*.rmdup.fxgrp.bam
rm -rf ${output_dir}/*.rmdup.fxgrp.bai
